version: '2'
services:
  deploy:
    image: polymerase-deploy:1.0
    build:
      context: .
      dockerfile: deploy
      args: 
        HOST_USER: ${USER}
    command: break-me
    volumes:
      - $PWD:/var/www/html
    volumes_from: 
      - warehouse
  web:
    image: polymerase-web:1.0
    build:
      context: .
      dockerfile: web
    volumes:
      - $PWD:/var/www/html
    ports:
      - 80:80
    links:
      - mariadb
  mariadb:
    image: polymerase-mariadb:10.2
    volumes_from:
      - warehouse
    ports:
      - "3306:3306"
    environment:
      # Only for development
      - MYSQL_ROOT_PASSWORD=rna
  warehouse:
    image: php:7.0.18-apache
    volumes:
      - /var/lib/mysql
      - /.composer
    command: break-me